# Generated by Django 4.1.7 on 2023-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instafetch', '0004_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='secretPassword',
            field=models.CharField(default='', max_length=50),
        ),
    ]
